### ISSUE TITLE
Nginx 1.9.0 Compilation

### ISSUE THREAD

**Issue by NodexTech** [vision5/ngx_devel_kit#10]
ngx_http_lua_timer.c:351: undefined reference to `ngx_http_set_connection_log'

When performing "make"

It forces the compiler to exit out.

The issue is not there on nginx 1.8.0

**Comment by ghost** [comment]
This isn't an NDK bug, it's an ngx_lua one.  See here: https://github.com/openresty/lua-nginx-module/blob/master/src/ngx_http_lua_timer.c

**Comment by agentzh** [comment]
@NodexTech I believe this has already been fixed in the latest git master of lua-nginx-module. Will you try it out on your side? Thanks!

**Comment by ghost** [comment]
I'm not doing ngx-lua stuff at the moment, and don't really have the time to look into it right now, but obviously if you're not getting compilation errors, then it's fixed.
