### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by sechacking** [vision5/ngx_devel_kit#15]
[root@webgw01 openresty-1.9.7.4]# make
cd /data/soft/openresty-1.9.7.4/build/LuaJIT-2.1-20160108 && make TARGET_STRIP=@: CCDEBUG=-g CC=cc PREFIX=/usr/local/openresty/luajit
make[1]: 进入目录“/data/soft/openresty-1.9.7.4/build/LuaJIT-2.1-20160108”
==== Building LuaJIT 2.1.0-beta1 ====
make -C src
make[2]: 进入目录“/data/soft/openresty-1.9.7.4/build/LuaJIT-2.1-20160108/src”
make[2]: 对“default”无需做任何事。
make[2]: 离开目录“/data/soft/openresty-1.9.7.4/build/LuaJIT-2.1-20160108/src”
==== Successfully built LuaJIT 2.1.0-beta1 ====
make[1]: 离开目录“/data/soft/openresty-1.9.7.4/build/LuaJIT-2.1-20160108”
cd /data/soft/openresty-1.9.7.4/build/lua-cjson-2.1.0.3 && make DESTDIR= LUA_INCLUDE_DIR=/data/soft/openresty-1.9.7.4/build/luajit-root/usr/local/openresty/luajit/include/luajit-2.1 LUA_CMODULE_DIR=/usr/local/openresty/lualib LUA_MODULE_DIR=/usr/local/openresty/lualib CJSON_CFLAGS="-g -fpic" CC=cc
make[1]: 进入目录“/data/soft/openresty-1.9.7.4/build/lua-cjson-2.1.0.3”
cc -c -O3 -Wall -pedantic -DNDEBUG  -I/data/soft/openresty-1.9.7.4/build/luajit-root/usr/local/openresty/luajit/include/luajit-2.1 -g -fpic -o lua_cjson.o lua_cjson.c
cc -c -O3 -Wall -pedantic -DNDEBUG  -I/data/soft/openresty-1.9.7.4/build/luajit-root/usr/local/openresty/luajit/include/luajit-2.1 -g -fpic -o strbuf.o strbuf.c
cc -c -O3 -Wall -pedantic -DNDEBUG  -I/data/soft/openresty-1.9.7.4/build/luajit-root/usr/local/openresty/luajit/include/luajit-2.1 -g -fpic -o fpconv.o fpconv.c
cc  -shared -o cjson.so lua_cjson.o strbuf.o fpconv.o
make[1]: 离开目录“/data/soft/openresty-1.9.7.4/build/lua-cjson-2.1.0.3”
cd /data/soft/openresty-1.9.7.4/build/lua-redis-parser-0.12 && make DESTDIR= LUA_INCLUDE_DIR=/data/soft/openresty-1.9.7.4/build/luajit-root/usr/local/openresty/luajit/include/luajit-2.1 LUA_LIB_DIR=/usr/local/openresty/lualib CC=cc
make[1]: 进入目录“/data/soft/openresty-1.9.7.4/build/lua-redis-parser-0.12”
cc -c -g -O -Wall -fpic -I/data/soft/openresty-1.9.7.4/build/luajit-root/usr/local/openresty/luajit/include/luajit-2.1   -o redis-parser.o redis-parser.c
cc -shared -o parser.so redis-parser.o
make[1]: 离开目录“/data/soft/openresty-1.9.7.4/build/lua-redis-parser-0.12”
cd /data/soft/openresty-1.9.7.4/build/lua-rds-parser-0.06 && make DESTDIR= LUA_INCLUDE_DIR=/data/soft/openresty-1.9.7.4/build/luajit-root/usr/local/openresty/luajit/include/luajit-2.1 LUA_LIB_DIR=/usr/local/openresty/lualib CC=cc
make[1]: 进入目录“/data/soft/openresty-1.9.7.4/build/lua-rds-parser-0.06”
cc -c -g -O -Wall -fpic -I/data/soft/openresty-1.9.7.4/build/luajit-root/usr/local/openresty/luajit/include/luajit-2.1   -o src/rds_parser.o src/rds_parser.c
cc -shared -o parser.so src/rds_parser.o
make[1]: 离开目录“/data/soft/openresty-1.9.7.4/build/lua-rds-parser-0.06”
cd /data/soft/openresty-1.9.7.4/build/nginx-1.9.7 && make
make[1]: 进入目录“/data/soft/openresty-1.9.7.4/build/nginx-1.9.7”
make -f objs/Makefile
make[2]: 进入目录“/data/soft/openresty-1.9.7.4/build/nginx-1.9.7”
objs/Makefile:131: **\* 遗漏分隔符  (您的意思是用 TAB 代替 8 个空格？)。 停止。
make[2]: 离开目录“/data/soft/openresty-1.9.7.4/build/nginx-1.9.7”
make[1]: **\* [build] 错误 2
make[1]: 离开目录“/data/soft/openresty-1.9.7.4/build/nginx-1.9.7”
make: **\* [all] 错误 2
[root@webgw01 openresty-1.9.7.4]#

**Comment by ghost** [comment]
This has nothing to do with NDK. 

Please

a) check that you have an error, because all the lines you posted look like valid make output
b) if you actually have an error, post it with Openresty - they're very responsive and helpful
c) take more care in the future to identify actual problems and post them in the right place

I've not done an Openresty install in a while, but the output to me looks like it was all done correctly.

Did you look in

**Comment by ghost** [comment]
/data/soft/openresty-1.9.7.4/build/nginx-1.9.7? (Sorry, on a phone - will fix previous post with this addition later.)
