### ISSUE TITLE
nginx 1.10 error

### ISSUE THREAD

**Issue by louishot** [vision5/ngx_devel_kit#17]
./configure --add-module=../ngx_devel_kit-master --add-module=../set-misc-nginx-module-master 
make
cc -c -fPIC -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -DNDK_SET_VAR -DNDK_UPSTREAM_LIST -I src/core -I src/event -I src/event/modules -I src/os/unix -I ../ngx_devel_kit-master/objs -I objs/addon/ndk -I ../ngx_devel_kit-master/src -I ../ngx_devel_kit-master/objs -I objs/addon/ndk -I objs -I src/http -I src/http/modules -I ../ngx_devel_kit-master/src \
    -o objs/addon/src/ndk.o \
    ../ngx_devel_kit-master/src/ndk.c
In file included from ../ngx_devel_kit-master/src/ndk.c:6:0:
../ngx_devel_kit-master/src/ndk.h:36:27: fatal error: ndk_config.h: No such file or directory
 #include    <ndk_config.h>
                           ^
compilation terminated.
objs/Makefile:1174: recipe for target 'objs/addon/src/ndk.o' failed
make[1]: **\* [objs/addon/src/ndk.o] Error 1
make[1]: Leaving directory '/home/pkg/nginx-1.10.1'
Makefile:8: recipe for target 'build' failed
make: **\* [build] Error 2

**Comment by ghost** [comment]
Hi,

ndk_config.h is a file that is automatically generated, and is found in the ../ngx_devel_kit-master/objs folder using the output you posted.

Please check that is there.  It may have been accidentally removed, or if you ran the autobuild function, then it may not have been generated properly.

If the file is not there, then you can either download the whole repo again (recommended solution), or run the auto/build script to re-generate the files (which should probably work, too).

Let me know if you still have problems, and if you don't, then please close the issue - if you can of course. :-)

**Comment by agentzh** [comment]
@holinhot The `-fPIC` option in your output looks strange. Your `./configure` command given above should never add that option. Are you sure your post is exactly correct?

**Comment by wgzwgz** [comment]
@holinhot Do you have solved this problem? I have this same problem!!!!! @simpl can you give a specific method! thank you!

**Comment by simpl** [comment]
@wgzwgz Did you get this problem solved?  You should be able to see usage examples here : https://github.com/openresty/lua-nginx-module#installation
