### ISSUE TITLE
Issue with building RPM package (undefined symbol: ndk_set_var_value)

### ISSUE THREAD

**Issue by bborysenko** [vision5/ngx_devel_kit#18]
Hello,

I have tried to build separate rpm package from this [spec](https://gist.github.com/bborysenko/31b83b284dc4f72555e4f55b31179842).

But when I install rpm package and try to use it with `ngx_http_lua_module` I got following error:

```
[root@5afe4843ca60 /]# grep load_module /etc/nginx/nginx.conf
load_module modules/ndk_http_module.so;
load_module modules/ngx_http_lua_module.so;

[root@5afe4843ca60 /]# nginx -t -c /etc/nginx/nginx.conf
nginx: [emerg] dlopen() "/etc/nginx/modules/ngx_http_lua_module.so" failed (/etc/nginx/modules/ngx_http_lua_module.so: undefined symbol: ndk_set_var_value) in /etc/nginx/nginx.conf:9
nginx: configuration file /etc/nginx/nginx.conf test failed
```

Could you please advice me what can be the issue? 

Thanks in advance.

**Comment by defanator** [comment]
Hi @bborysenko,

try to add `-DNDK_SET_VAR -DNDK_UPSTREAM_LIST` to the `--with-cc-opt` configure directive parameters, i.e. the whole directive should be:

    --with-cc-opt="%{WITH_CC_OPT} -DNDK_SET_VAR -DNDK_UPSTREAM_LIST"

This should be enough for the Lua module to load and operate.

You may want to check the sources for other possible defines (but please check the README about using `NDK_ALL`).

Hope this helps.

**Comment by bborysenko** [comment]
@defanator Thanks a lot! `NDK_SET_VAR` should be quite enough for lua.
