### ISSUE TITLE
How to start

### ISSUE THREAD

**Issue by pradeepitm12** [vision5/ngx_devel_kit#23]
I want to write a module over Nginx.
First I tried with cloning Nginx and writing my module in it, every time I was getting import error for #include <ngx_config.h>.
Then I found NDK. But when I am importing NDK into eclipse for c then too I am getting same error.
Need help to take first step. How to use it.
1) How can I start to develop a module with NDK and run it.... 
2) How to compile NDK

**Comment by mclyne** [comment]
@pradeepitm12 Sorry for the very late reply.  I've not been at my computer in months.  Have you worked it all out now?

**Comment by simpl** [comment]
@pradeepitm12 Sorry for the very late reply. I've not been at my computer in months. Have you worked it all out now?

**Comment by simpl** [comment]
@pradeepitm12 Sorry for the very late reply, and possibly slightly confusing messages you've received from GitHub. I've not been at my computer in months, and have converted the @simpl account into an organization. Have you worked it all out now?  You might want to check out https://github.com/openresty/lua-nginx-module#installation.  I'll close the issue for now, but feel free to re-open it if you're still having trouble.  Again, sorry for the long delay in responding.

**Comment by pradeepitm12** [comment]
Hey, no issues Right now I am working on another project, whenever I will
get back to that project I will let you know.

**Comment by simpl** [comment]
OK, no worries.  I should be more responsive in the future. ;-)  Good luck with whatever you're working on. :-)
