### ISSUE TITLE
Fail to link module with nginx as dynamic library

### ISSUE THREAD

**Issue by deepakjeena** [vision5/ngx_devel_kit#24]
Hi,
I am facing problem with this module, module successfully complited but when i configure this with NGINX, I am getting below error. 
I have successfully complied and configured other modules with nginx. But same not working with this, I changed build conguration, still no success. Please help

**## ERROR** 
nginx: [emerg] module "/etc/nginx/modules/ndk_http_module.so" is not binary compatible in /etc/nginx/nginx.conf:1
nginx: configuration file /etc/nginx/nginx.conf test failed

**## NGINX build configuration**

./configure --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fPIC' --with-ld-opt='-Wl,-z,relro -Wl,-z,now -pie' --add-dynamic-module=../ngx_devel_kit-master/ --add-dynamic-module=../lua-nginx-module-master/

**Comment by defanator** [comment]
@deepakjeena you should add `--with-compat` configure option in both scenarios (building nginx / building dynamic module for nginx).

**Comment by simpl** [comment]
@deepakjeena 

https://forum.nginx.org/read.php?29,270210,270213#msg-270213

Please close this issue if you have no further issues.  

Thanks!

**Comment by deepakjeena** [comment]
@defanator thanks.
