### ISSUE TITLE
module "/etc/nginx/modules/ngx_http_js_module.so" version 1017008 instead of 1016001 in /etc/nginx/nginx.conf:5

### ISSUE THREAD

**Issue by satscreate** [vision5/ngx_devel_kit#27]
```
nginx -v
nginx version: nginx/1.16.1

```
Grabbed,
`ngx_devel_kit-0.3.1`

But build with below command,
`./configure --with-compat --add-dynamic-module=/tmp/nginx_stable/ngx_devel_kit-0.3.1`

Please help

**Comment by simpl** [comment]
The NDK can't be built as a dynamic module.  Not all Nginx modules can be dynamic.  Only modules that have the specific code in the module files to be built as dynamic modules can be dynamic.

Also, if you look at your error information, it's to do with the ngx_http_js_module - not NDK.
