### ISSUE TITLE
Differences in downloaded tags

### ISSUE THREAD

**Issue by tuplebunny** [vision5/ngx_devel_kit#29]
Hello.  I don't know if this is a repository-specific issue, or a GitHub issue. I have already e-mailed GitHub about this. I am posting here just in case.

Here is what I am seeing:

I go here:
https://github.com/vision5/ngx_devel_kit/releases

And I download the file at this link:
https://github.com/vision5/ngx_devel_kit/archive/refs/tags/v0.3.1.tar.gz

I can also download the file at this link:
https://github.com/vision5/ngx_devel_kit/archives/refs/tags/v0.3.1.tar.gz

The 2 links are equal, except s/archive/archives/.

And the files downloaded are different sizes.

The file at /archive/ is ~65K.

The file at /archives/ is ~74K.

What is going on?

Cheers,

- Daniel

**Comment by simpl** [comment]
Sorry for the late reply.  I only just saw your post.

- https://github.com/vision5/ngx_devel_kit/archive/refs/tags/v0.3.1.tar.gz is the correct URL
- https://github.com/vision5/ngx_devel_kit/archives/refs/tags/v0.3.1.tar.gz is an incorrect URL.  You're downloading the 404 page (I'm guessing).  I don't get anything that's ~74K.

There aren't any /archives/ URLs on that page - at least not now.  If there was a Github issue, then it looks like it's been resolved.  Am closing this issue.

Thanks.
