### ISSUE TITLE
error with set_misc

### ISSUE THREAD

**Issue by ghost** [vision5/ngx_devel_kit#36]
Hi! After update this module don`t work with ngx_http_set_misc_module

nginx: [emerg] dlopen() "/etc/nginx/modules/ngx_http_set_misc_module.so" failed (/etc/nginx/modules/ngx_http_set_misc_module.so: undefined symbol: ndk_set_var_value) in /etc/nginx/nginx.conf:12
nginx: configuration file /etc/nginx/nginx.conf test failed

**Comment by ghost** [comment]
I think something with compilation:
Old version (WORK): https://www.sendspace.com/file/blmby2
New version: https://www.sendspace.com/file/u0bimg

I tried to compile with different versions 1.22.1 and 1.24.0, both options do not work...OS RockyOS 9.1

**Comment by simpl** [comment]
@kurgachel Which sources are you using and what's the full command you're using to ./configure?

You may find it easier to use an OpenResty package: https://openresty.org/en/download.html

**Comment by ghost** [comment]
sudo git clone https://github.com/vision5/ngx_devel_kit
configure --modules-path=/etc/nginx/modules --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/etc/nginx/log/error.log --pid-path=/var/run/nginx.pid --lock-path=/var/lock/nginx.lock --http-log-path=/dev/null --prefix=/var/lib/nginx --with-http_geoip_module --with-http_ssl_module --with-http_gzip_static_module --with-http_v2_module --with-stream --with-compat --with-openssl=/usr/local/src/openssl-1.1.1t --add-dynamic-module=/home/rocky/nginx-module-vts --add-dynamic-module=/home/rocky/testcookie-nginx-module --add-dynamic-module=/home/rocky/ngx_brotli --add-dynamic-module=/home/rocky/ngx_devel_kit

**Comment by simpl** [comment]
Try:
--add-module=/home/rocky/ngx_devel_kit
instead of
--add-dynamic-module=/home/rocky/ngx_devel_kit

The dynamic loader is trying to load ngx_http_set_misc_module.so, but there's a missing symbol ndk_set_var_value, which is part of the nginx development kit.

**Comment by ghost** [comment]
In nginx.conf
load_module /etc/nginx/modules/ndk_http_module.so;
load_module /etc/nginx/modules/ngx_http_set_misc_module.so;

It worked before

**Comment by simpl** [comment]
It could be that the ngx_http_set_misc_module has changed so that when the shared object is loaded, it doesn't automatically load the NDK library as a shared object.  This is outside the scope of the NDK, though, and should be addressed in the set misc module, if needs be.

Does it work now using --add-module=...?

**Comment by ghost** [comment]
> Does it work now using --add-module=...?

same...don`t work

**Comment by simpl** [comment]
Try using the OpenResty package above.  That's checked to verify that the packages work together, and it includes the set misc module.

Note: You'll also need to remove the lines

load_module /etc/nginx/modules/ndk_http_module.so;
...

Since you won't be loading them dynamically.
